### ISSUE TITLE
Documentation is needed

### ISSUE THREAD

**Issue by chanon** [scalegenius/pg_bitemporal#21]
Hello, I watched your talk and then read that you are also using it in production now, so that makes it a very interesting library for people who may want to use bitemporal tables!

However, right now there is not really any documentation (other than the talk). 

I know you are likely very busy, and I can maybe look at the tests for some examples ... but if there was a list of available functions with explanation and examples and maybe some best practice/tips, that would be great!

**Comment by hettie-d** [comment]
Thank you so much for your interest! We are indeed busy, but we will definitely try to provide better documentation, and I hope to give another talk on one of the conferences this fall. Please feel free to reach out at henr33@gmail.com

**Comment by Skeen** [comment]
Please consider prioritizing documentation. I'd love to utilize this code in a project, but with the current state of documentation and examples, I'm very weary of doing so.

**Comment by hettie-d** [comment]
I will do my  best! If nothing will appear within a week feel free to express your anger and frustration :)

**Comment by Skeen** [comment]
@hettie-d I have anger and frustration now

**Comment by hettie-d** [comment]
We've just pushed some documentation to the master branch.  This document
https://github.com/scalegenius/pg_bitemporal/blob/master/docs/pg_bitemporal_reference.md

has documentation on about half of the function.  Could you please give me feedback on whether this is enough level of detail? I will work on documenting the rest of the functions
 over the weekend.Thank you so much for your interest in our work!

**Comment by hettie-d** [comment]
Also,  you can find a more recent presentation on the usage of pg_bitemporal in the docs directory.

**Comment by hettie-d** [comment]
At the moment, all bitemporal functions are documented to some degree. All feedback will be appreciated!
