### ISSUE TITLE
Getting started questions for a total newbie

### ISSUE THREAD

**Issue by albert-kam** [scalegenius/pg_bitemporal#31]
Hi there. 

During my mission on finding out ways to implement slowly changing dimensions in Postgresql, i noticed that Bitemporal might be a better fit for my needs, which is audit reports, being able to go back in time for reports, etc.

I have watched the 2016 PG Open presentation video on youtube, and as a total newcomer, i would like to understand a few things conceptually before trying it out.

1. Please correct me if my assumptions are wrong. To get started, i'd need to: 
    1. Create my 'normal' table, which reflects the 'current' state
    2. Create my bitemporal table to store audits using ll_create_bitemporal_table
    3. Every updates in the 'normal' table must be followed by bl_bitemporal_insert, cannot use trigger for automatic auditing to bitemporal table since we need to be specific for the effective n assertive date.

2. For SCD classic scenario, where an employee record could have it's 'branch' field changed multiple times because of moving locations of offices, how do i join an old sales order record for that employee to the bitemporal table so that i can get the correct employee branch relative to the date of the old sales order transaction date ? I know this could be basic sql, but any pointers would be greatly appreciated.

Thank you so much for these tools.

**Comment by hettie-d** [comment]
Hi! Thank you for your interest in our project!  Actually, things work way easier (or more complicated:)) than you described.
You only need one table for everything, both current status and history are stored in one table, the current record is characterized by the fact that it is "effective now" which means that the upper(effective)='infinity' and upper (asserted)='infinity'

OR 

now()<@ effective and now()<@asserted.
When you create your bitemporal table, you need to define your business key, which will be, say  eployee_id. You can think of it as "bitemporal primary key" - there will be multiple records with this ID, but all of them will describe one object (one person)
When your employee changes location, you can issue a bitemporal update for this business key with new location id. 

If you look at the documentation directory, you can find some of my presentations where I explain the usage in detail. Also, if you want to give me a sample DDL of your table, I can provide you the exact statements you will need.
In my organization, we run all databases, both OLTP and OLAP on the bitemporal framework, and we have no performance problems.
Feel free to reach out with further questions. Thank you!

**Comment by albert-kam** [comment]
Dear Hettie,

Thank you so much for the quick and detailed helps !

I will setup a use case, try out the commands first before coming back to you with more in the next week. Hopefuly this can also eventually serve as a quick starting guide for other beginners like me.

**Comment by hettie-d** [comment]
That was my thought exactly!  It can be an excellent example for future users!

**Comment by albert-kam** [comment]
Dear Hettie,

I hope you and family are well in this challenging time.
I am super late following up our previous discussion because of understaffing and emergency issues, but your bitemporal tables still haunts me deep down inside.

Now i have come up with a simple ddl, and simple sql statements to demonstrate the usual case of slowly changing dimension.
I hope you could help me translate into bitemporal table and show the usage of the script you guys made.

The ddl and dml are made transactional, and can be re-run to reset the tables with ease.
Basically i try to demonstrate making an order, containing information about the sales staff + customer, with a single item.
And with time, these informations change, and the looking back at the old order record now contains the newer information which is invalid.
Here goes:
```

# shell commands
su - postgres
createdb hettie
psql

# transactional ddl + dml, comments inside
BEGIN;

DROP TABLE IF EXISTS staff CASCADE;
CREATE TABLE staff
	(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	  name VARCHAR(255) NOT NULL,
          location VARCHAR(255) NOT NULL,
	  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

DROP TABLE IF EXISTS cust CASCADE;
CREATE TABLE cust
	(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	  name VARCHAR(255) NOT NULL,
          phone VARCHAR(255),
	  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

DROP TABLE IF EXISTS product CASCADE;
CREATE TABLE product
	(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	  name VARCHAR(255) NOT NULL,
          weight INTEGER NOT NULL DEFAULT(0),
          price INTEGER NOT NULL DEFAULT(0),
          deleted BOOLEAN NOT NULL DEFAULT(FALSE),
	  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

DROP TABLE IF EXISTS t_order CASCADE;
CREATE TABLE t_order
	(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	  staff_id INT NOT NULL REFERENCES staff(id),
          cust_id INT NOT NULL REFERENCES cust(id),
	  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

DROP TABLE IF EXISTS t_order_line CASCADE;
CREATE TABLE t_order_line
	(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
          order_id INT REFERENCES t_order(id),
	  product_id INT REFERENCES product(id),
          qty INTEGER NOT NULL,
	  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

INSERT INTO staff (name, location) VALUES ('mystaff', 'mylocation');
INSERT INTO cust (name, phone) VALUES ('mycust', '+6281197889890');
INSERT INTO product (name, weight, price) VALUES ('myproduct', 100, 200);
INSERT INTO t_order (staff_id, cust_id) VALUES (1, 1);
INSERT INTO t_order_line (order_id, product_id, qty) VALUES (1, 1, 10);

/* Try to display the order line with the correct info for the time of order transaction */
SELECT o.id AS order_id, s.name AS staff_name, s.location AS staff_location, c.name AS cust_name, c.phone AS cust_phone, p.name AS product_name, p.weight AS product_weight, p.price AS product_weight, l.qty AS quantity
    FROM t_order_line l
    JOIN t_order o ON o.id = l.order_id
    JOIN product p ON p.id = l.product_id
    JOIN staff s ON s.id = o.staff_id
    JOIN cust c ON c.id = o.cust_id;

/*
Results in:
 order_id | staff_name | staff_location | cust_name |   cust_phone   | product_name | product_weight | product_weight | quantity 
----------+------------+----------------+-----------+----------------+--------------+----------------+----------------+----------
        1 | mystaff    | mylocation     | mycust    | +6281197889890 | myproduct    |            100 |            200 |       10


Then we edit the existing records, and requery, to find out the info for the old order transaction has been incorrect 
*/

UPDATE staff SET location = 'newlocation' WHERE id = 1;
UPDATE product SET price = 300 WHERE id = 1;
UPDATE cust SET phone = '+6281111111111' WHERE id = 1;

SELECT o.id AS order_id, s.name AS staff_name, s.location AS staff_location, c.name AS cust_name, c.phone AS cust_phone, p.name AS product_name, p.weight AS product_weight, p.price AS product_weight, l.qty AS quantity
    FROM t_order_line l
    JOIN t_order o ON o.id = l.order_id
    JOIN product p ON p.id = l.product_id
    JOIN staff s ON s.id = o.staff_id
    JOIN cust c ON c.id = o.cust_id;

/*
Results in incorrect output for the old order:

 order_id | staff_name | staff_location | cust_name |   cust_phone   | product_name | product_weight | product_weight | quantity 
----------+------------+----------------+-----------+----------------+--------------+----------------+----------------+----------
        1 | mystaff    | newlocation    | mycust    | +6281111111111 | myproduct    |            100 |            300 |       10
*/

COMMIT;

```

**Comment by hettie-d** [comment]
I can't thank you enough! I was thinking that the current period of forced isolation can be used to finally address my extended to-do list for the bitemporal library. I am going to start working on the tutorial very soon. Not sure where you are located, but please stay safe wherever you are.

**Comment by hettie-d** [comment]
Hi @albert-kam ! You might find it hard to believe, but after all these months I put together a short bitemporal tutorial based on your example. I am going to present it at Chicago PUG this Wednesday (which I guess is out of your timezone), and I will add the code here

**Comment by hettie-d** [comment]
@albert-kam - the tutorial is added!

**Comment by albert-kam** [comment]
My deepest gratitude, you are amazing !
Please stay safe and be well.

**Comment by hettie-d** [comment]
:)
