### ISSUE TITLE
Issue updating bitemporal entries

### ISSUE THREAD

**Issue by Skeen** [scalegenius/pg_bitemporal#36]
#### Issue description
I seem unable to update a row in bitemporal entries more than once.

#### Steps to reproduce the issue
1.  Start a `postgres` `9` in docker:
```
$ docker run -it -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 postgres:9
```

2. Load SQL procedures:
```
$ cat _load_all.sql | psql -h 127.0.0.1 -U postgres
...
CREATE FUNCTION
COMMIT
```

3. Open a `psql` connection:
```
$ psql -h 127.0.0.1 -U postgres
```
The following steps are executing within this REPL.

4.  Create a new schema:
```
=# CREATE SCHEMA bi_temp_tables;
CREATE SCHEMA
```

5. Create a bitemporal table using `bitemporal_internal.ll_create_bitemporal_table`:
```
=# select * from bitemporal_internal.ll_create_bitemporal_table(
   'bi_temp_tables','devices', 'device_id integer, device_descr text', 'device_id'
);

 ll_create_bitemporal_table 
----------------------------
 t
(1 row)
```

6. List the table to see that it was created correctly:
```
=# SELECT * FROM bi_temp_tables.devices;

 devices_key | device_id | device_descr | effective | asserted | row_created_at 
-------------+-----------+--------------+-----------+----------+----------------
(0 rows)
```

7. Insert an entry using `bitemporal_internal.ll_bitemporal_insert`:
```
=# select * from bitemporal_internal.ll_bitemporal_insert(
    'bi_temp_tables.devices',
    'device_id ,
    device_descr',
    $$1,
    'description_1'$$,
    '[2010-01-01, infinity)'::tstzrange,
    '[2019-07-08 09:33:20, infinity)'::tstzrange
);
 ll_bitemporal_insert 
----------------------
                    1
(1 row)
```

8. Check the result:
```
=# SELECT * FROM bi_temp_tables.devices;
 devices_key | device_id | device_descr  |              effective              |              asserted               |        row_created_at         
-------------+-----------+---------------+-------------------------------------+-------------------------------------+-------------------------------
           1 |         1 | description_1 | ["2010-01-01 00:00:00+00",infinity) | ["2019-07-08 09:33:20+00",infinity) | 2020-07-08 07:33:18.082932+00
(1 row)
```

9. Update the entry using `bitemporal_internal.ll_bitemporal_update`:
```
=# select * from bitemporal_internal.ll_bitemporal_update(
    'bi_temp_tables',
    'devices',
    'device_descr',
    $$'Valid from 2020-01-01'$$,
    'device_id',
    $$1$$,
    '[2020-01-01, infinity)',
    '[2020-07-08 09:35:20, infinity)'
);
 ll_bitemporal_update 
----------------------
                    1
(1 row)
```

10. Check the result:
```
=# SELECT * FROM bi_temp_tables.devices;
 devices_key | device_id |     device_descr      |                      effective                      |                      asserted                       |        row_created_at         
-------------+-----------+-----------------------+-----------------------------------------------------+-----------------------------------------------------+-------------------------------
           1 |         1 | description_1         | ["2010-01-01 00:00:00+00",infinity)                 | ["2019-07-08 09:33:20+00","2020-07-08 09:35:20+00") | 2020-07-08 07:33:18.082932+00
           2 |         1 | description_1         | ["2010-01-01 00:00:00+00","2020-01-01 00:00:00+00") | ["2020-07-08 09:35:20+00",infinity)                 | 2020-07-08 07:35:58.920979+00
           3 |         1 | Valid from 2020-01-01 | ["2020-01-01 00:00:00+00",infinity)                 | ["2020-07-08 09:35:20+00",infinity)                 | 2020-07-08 07:35:58.920979+00
(3 rows)
```

11. Attempt to make another update to the entry using `bitemporal_internal.ll_bitemporal_update`:
```
=# select * from bitemporal_internal.ll_bitemporal_update(
    'bi_temp_tables',
    'devices',
    'device_descr',
    $$'Valid from 2020-05-01'$$,
    'device_id',
    $$1$$,
    '[2020-05-01, infinity)',
    '[2020-07-08 09:37:20, infinity)'
);
```

#### What's the expected result?
At this point, the expected output is:
```
 ll_bitemporal_update 
----------------------
                    1
(1 row)
```
And checking the result, should yield:
```
=# SELECT * FROM bi_temp_tables.devices;
 devices_key | device_id |     device_descr      |                      effective                      |                      asserted                       |        row_created_at         
-------------+-----------+-----------------------+-----------------------------------------------------+-----------------------------------------------------+-------------------------------
           1 |         1 | description_1         | ["2010-01-01 00:00:00+00",infinity)                 | ["2019-07-08 09:33:20+00","2020-07-08 09:35:20+00") | 2020-07-08 07:33:18.082932+00
           2 |         1 | description_1         | ["2010-01-01 00:00:00+00","2020-01-01 00:00:00+00") | ["2020-07-08 09:35:20+00","2020-07-08 09:37:20+00") | 2020-07-08 07:35:58.920979+00
           3 |         1 | Valid from 2020-01-01 | ["2020-01-01 00:00:00+00",infinity)                 | ["2020-07-08 09:35:20+00","2020-07-08 09:37:20+00") | 2020-07-08 07:35:58.920979+00
           4 |         1 | description_1         | ["2010-01-01 00:00:00+00","2020-01-01 00:00:00+00") | ["2020-07-08 09:37:20+00",infinity)                 | 2020-07-08 07:37:48.221479+00
           5 |         1 | Valid from 2020-01-01 | ["2020-01-01 00:00:00+00","2020-05-01 00:00:00+00") | ["2020-07-08 09:37:20+00",infinity)                 | 2020-07-08 07:37:48.221479+00
           6 |         1 | Valid from 2020-05-01 | ["2020-05-01 00:00:00+00",infinity)                 | ["2020-07-08 09:37:20+00",infinity)                 | 2020-07-08 07:37:48.221479+00
(6 rows)
```

#### What's the actual result?
After running the second update query the following result is produced:
```

ERROR:  conflicting key value violates exclusion constraint "devices_device_id_assert_eff_excl"
DETAIL:  Key (device_id, asserted, effective)=(1, ["2019-07-08 09:33:20+00","2020-07-08 09:37:20+00"), ["2010-01-01 00:00:00+00",infinity)) conflicts with existing key (device_id, asserted, effective)=(1, ["2020-07-08 09:35:20+00",infinity), ["2010-01-01 00:00:00+00","2020-01-01 00:00:00+00")).
CONTEXT:  SQL statement " WITH updt AS (UPDATE bi_temp_tables.devices SET asserted =
            temporal_relationships.timeperiod(lower(asserted), lower('["2020-07-08 09:37:20+00",infinity)'::temporal_relationships.timeperiod))
                    WHERE ( device_id )=( 1 ) AND (temporal_relationships.is_overlaps(effective, '["2020-05-01 00:00:00+00",infinity)')
                                       OR 
                                       temporal_relationships.is_meets(effective::temporal_relationships.timeperiod, '["2020-05-01 00:00:00+00",infinity)')
                                       OR 
                                       temporal_relationships.has_finishes(effective::temporal_relationships.timeperiod, '["2020-05-01 00:00:00+00",infinity)'))
                                      AND now()<@ asserted  returning devices_key )
                                      SELECT array_agg(devices_key) FROM updt
                                      "
PL/pgSQL function bitemporal_internal.ll_bitemporal_update(text,text,text,text,text,text,temporal_relationships.timeperiod,temporal_relationships.timeperiod) line 30 at EXECUTE
```

**Comment by hettie-d** [comment]
Hi! The problem occurs because you apply two subsequent updates with a future assertion. I suspect, that when you were executing these SQL statements, your asserted interval started in the future. In the majority of real-life cases, we assert at the  present moment, meaning that asserted= temporal_relationships.timeperiod(now(), 'infinity') 
Although we allow future assertions, we do not allow two subsequent future assertions. We are planning to suggest some algorithm to resolve such situations, but we do not have it now. The problem with future assertion is that we need to decide, whether we allow "future-future overwrite". So, at the moment, this is the correct behavior. If you issue the same update with temporal_relationships.timeperiod(now(), 'infinity') , there will be no conflicts. Hope that helps!

**Comment by Skeen** [comment]
> Hi! The problem occurs because you apply two subsequent updates with a future assertion. I suspect, that when you were executing these SQL statements, your asserted interval started in the future. In the majority of real-life cases, we assert at the present moment, meaning that asserted= temporal_relationships.timeperiod(now(), 'infinity')
> Although we allow future assertions, we do not allow two subsequent future assertions. We are planning to suggest some algorithm to resolve such situations, but we do not have it now. The problem with future assertion is that we need to decide, whether we allow "future-future overwrite". So, at the moment, this is the correct behavior. If you issue the same update with temporal_relationships.timeperiod(now(), 'infinity') , there will be no conflicts. Hope that helps!

But shouldn't this be okay, when the second update happens after the asserted start time is in the past. As you can see, the second update is later than the asserted start time of the previous update?

- I just noticed the two hour offset, which is probably due to timezones. So disregard the statement about it actually being passed.

**Comment by hettie-d** [comment]
Yes, when the first one already passed, you can apply one more future assertion. Just wanted to re-iterate that the reason we do not allow more than one future assertion is, that technically speaking, it can be anybody, not just you, making the first one. And you "can't see it" if you do not know it's in place. so you do are running into a conflict of overwriting the changes which didn't happen yet.

**Comment by Skeen** [comment]
> Yes, when the first one already passed, you can apply one more future assertion. Just wanted to re-iterate that the reason we do not allow more than one future assertion is, that technically speaking, it can be anybody, not just you, making the first one. And you "can't see it" if you do not know it's in place. so you do are running into a conflict of overwriting the changes which didn't happen yet.

Hi, yea that makes sense, and my use case wants to insert 'now()', I just didn't see the timezone offset.
