### ISSUE TITLE
How do you "release" this software?

### ISSUE THREAD

**Issue by jzabroski** [scalegenius/pg_bitemporal#38]
GitHub shows no use of Releases but @hettie-d  said on Hacker News that she is using this in production cf https://news.ycombinator.com/item?id=19733386

**Comment by hettie-d** [comment]
I am not sure what the question is. If the question is how to install it, you can clone this repo and run _load_all.sql. 

Also, we now have a lot of documentation and tutorial, just check out the docs and tutorial folders

**Comment by jzabroski** [comment]
The question is, how do you know what version of the software you're using is?

**Comment by hettie-d** [comment]
It's not software at the moment, because we do not have the capacity to maintain it properly, We would be glad to accept any offer of collaboration.

**Comment by jzabroski** [comment]
Well, my interest is non-zero, but realistically I have six months of various PRs I want to submit to various FLOSS projects.  I think the use of pgTap and other things increase the barrier for me to jump in and automate stuff.  I am simply not a PG/SQL expert, and while it doesn't intimidate me, I'm not exactly seeing the value in learning pgTap and becoming a PG/SQL expert :-)

My interest comes from a work in progress whitepaper I am writing regarding implementing Allen's interval algebra in SQL databases.  I did a proprietary solution for a client in 2018 but it was not optimal despite being easy for them to maintain and hitting their performance objectives on a 10B row TAQ table.
I thought it would be cool to have some official benchmarks for Postgres, plus encoding my interval algebra solution against various SQL databases using my open source SQL migration library FluentMigrator, and possibly kdb+ via TorQ library.

**Comment by hettie-d** [comment]
I wish we would be able to maintain it properly, but for all these past 5+ years it didn't become easier. We tried to get some interest from the Postgres core team, and we even had some positive feedback, but nothing came out of it. 
I personally do not think that any formal benchmarking proves anything because, at the end of the day, the important part is HOW you write your SQL, your function, your system.  I can produce an extremely performant SQL even in MySQL :). 

In any case, I really appreciate your interest in our project!

**Comment by jzabroski** [comment]
Benchmarking is a sensitive topic.  There are very few papers in Computer Science with rigorous approaches.  I personally believe this is due to the fact performance benchmarking statistical analysis is slightly different from traditional Prob & Stats taught in undergrad and Master's level courses.

However, as a brief example of a survey of benchmarking gone wrong, I usually refer to Chip Wright's papers on filesystem benchmarking from 2008. https://www.fsl.cs.sunysb.edu/docs/fsbench/fsbench.pdf But I do note that they had published frameworks for benchmarking in 2005 https://www.usenix.org/legacy/events/usenix05/tech/freenix/full_papers/wright/wright.pdf

Some of this becomes more institutionalized over time.  For example, BenchmarkDotNet project has brought more rigor to benchmarking .NET programs by bundling not only measurement but measurement analysis best practices.  Prior to this, it was a hodge podge of techniques and the quality of analysis varies greatly.

**Comment by hettie-d** [comment]
I would not argue with you on the topic of general software benchmarking, but the database performance is different. 
I am going to close this issue if it's OK with you - I messaged you on LinkedIn. A performance conversation may be lengthy :)
