### ISSUE TITLE
Reference doc says there are two functions for ll_bitemporal_update

### ISSUE THREAD

**Issue by raghavio** [scalegenius/pg_bitemporal#43]
https://github.com/teamohana/pg_bitemporal/blob/f783c21012d13c80f349fff71e3d394846a906f6/docs/pg_bitemporal_reference.md#ll_bitemporal_update
For `ll_bitemporal_update` update the doc says there are two signatures of it:
> We strongly recommend to use the latter one, the first signature is non-compatiable with PG 10 and up, and is retained solely for the backward compatiability, will be eventually retired. In addition, the performance of the second version is much better.

However the file has just one function present.

**Comment by hettie-d** [comment]
Hi @raghavio, yes, I didn't update the documentation after I eliminated the old version of the function, thank you for pointing it out.  
Please follow https://github.com/hettie-d/pg_bitemporal for future updates

**Comment by raghavio** [comment]
Hi @hettie-d, thanks for the quick update. Will follow that repo for future updates. I have created another issue regarding bitemporal update. It would be great if you could take a look at #44 as well.

**Comment by hettie-d** [comment]
Yes, I saw it, taking a look! It would be great if you could submit this issue to my fork - I have no permissions to commit to this repo, so from mow on, my fork will have the most recent changes

**Comment by raghavio** [comment]
Thanks @hettie-d. I was planning to do that but you don't have issue tracking enabled in your fork.

**Comment by hettie-d** [comment]
Oh, thank you - I've enabled issues! 
https://github.com/hettie-d/pg_bitemporal/issues
